repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.7
    hooks:
      - id: ruff
        args: [--fix, --show-fixes]  # auto fix
      - id: ruff-format

  - repo: https://github.com/pylint-dev/pylint
    rev: v3.3.7
    hooks:
      - id: pylint

  # commitlint - temporarily disabled due to configuration issue
  # - repo: https://github.com/conventional-changelog/commitlint
  #   rev: v19.8.1
  #   hooks:
  #     - id: commitlint
  #       additional_dependencies: ["@commitlint/config-conventional"]
