repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.7
    hooks:
      - id: ruff
        args: [--fix, --show-fixes]  # auto fix
      - id: ruff-format

  - repo: https://github.com/pylint-dev/pylint
    rev: v3.3.7
    hooks:
      - id: pylint

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.29.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
